# Generated by Django 5.0.7 on 2024-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_video_video_480p_video_video_720p'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='content.video'),
        ),
    ]
