# Generated by Django 5.0.7 on 2024-08-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
