# Generated by Django 5.0.7 on 2024-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
