# Generated by Django 5.0.7 on 2024-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video_video_file_480p_video_video_file_720p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p'),
        ),
    ]
