# Generated by Django 5.0.7 on 2024-08-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_480p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_720p',
        ),
    ]
